In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../Python/Churn_Modelling.csv')

df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:

X = df.iloc[:, 3:13].values
y= df.iloc[:,13].values

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [13]:
# Encoding categorical data

from sklearn.preprocessing import OneHotEncoder, LabelEncoder

labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
# Splitting the dataset to training and test set
from sklearn.model_selection import train_test_split

X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [15]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##### Classical Decision tree model

In [16]:
# Classical ML
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
pred = clf.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)

print(cm)

[[1375  220]
 [ 189  216]]


In [18]:
from sklearn.metrics import accuracy_score

accuracyScore = accuracy_score(y_test, pred)

print(accuracyScore)

0.7955


##### ANN

In [19]:
# Importing keras libraries and packages

import keras
from keras.models import Sequential
from keras.layers import Dense

In [20]:
# Initialsing the ANN
classifier = Sequential()

# units = Neurons, It's an art, comes by experience, input+output/2
# Initialiser  = how your weights are updated
# relu activation function
# input_dim = input shape( shape of the data, how many features do we have in data)

# Adding the input layer and first hidden layer
classifier.add(Dense(units=6, kernel_initializer ='uniform', activation='relu', input_dim=10))

# Adding the second hidden layer
classifier.add(Dense(units=6, kernel_initializer ='uniform', activation='relu'))

# Adding the third hidden layer
classifier.add(Dense(units=6, kernel_initializer ='uniform', activation='relu'))

# Adding the output layer
classifier.add(Dense(units=1, kernel_initializer ='uniform', activation='sigmoid'))






c:\Users\HP\Desktop\Interview Prep\AI Engineer\.venv\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
# Compiling the ANN

classifier.compile(optimizer ='adam', loss='binary_crossentropy', metrics =['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size=200, epochs= 20)

Epoch 1/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.7948 - loss: 0.6897
Epoch 2/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7982 - loss: 0.6698
Epoch 3/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.6189
Epoch 4/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8030 - loss: 0.5171
Epoch 5/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8057 - loss: 0.4519
Epoch 6/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7916 - loss: 0.4547
Epoch 7/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7895 - loss: 0.4532
Epoch 8/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7968 - loss: 0.4432
Epoch 9/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7956 - loss: 0.4426
Epoch 10/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7937 - loss: 0.4417
Epoch 11/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.4284
Epoch 12/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8002 - l

In [23]:
# Making predictions and evaluating the model
# Predicting the test set results

y_pred_Ann = classifier.predict(X_test)
y_pred_Ann = (y_pred_Ann > 0.5)

cm2 = confusion_matrix(y_test, y_pred_Ann)
print(cm2)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[[1595    0]
 [ 405    0]]


In [24]:
# Accuracy Score
from sklearn.metrics import accuracy_score

score =accuracy_score(y_test, y_pred_Ann)
print(score*100)

79.75


##### Conclusion

So, as we have already seen, by using 2 hidden layered ANN, we aren't able to get beyond 80% accuracy, ofcourse we can get higher accuracy by increasing the epochs & doing some hyperparameter optimisation, so on the other hand, classical ML models can be tuned further.

Bottomline, always start with classical machine learning models and if we arent able to increase the performance, then move towards deep learning technique.

In [25]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = classifier.predict(sc.transform(np.array([[600, 0, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction
# Making the Confusion Matrix
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step


array([[False]])

In [27]:
import keras

In [29]:
import tensorflow 

In [31]:
pip install scikeras

Note: you may need to restart the kernel to use updated packages.


What is K-Fold Cross Validation?

It’s a technique to evaluate how well your model generalizes —
meaning: how good your model will perform on unseen data (not just the data it was trained on).

Instead of doing one single train-test split, K-Fold CV splits your dataset into K parts (folds) and runs training + testing K times — each time using a different fold as the test set.

In [33]:
#Importing few libraries for k-folds cross validation on a Keras deep learning model using scikit-learn’s wrapper.

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

#Defining the neural network
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

# Wrapping it into a scikit-learn compatible classifier
classifier = KerasClassifier(model = build_classifier, batch_size = 10, epochs = 10)

# So now classifier behaves like a normal scikit-learn model (with .fit() and .predict() methods).

# Applying K-Fold Cross Validation
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv =10, n_jobs = -1 )
mean1 = accuracies.mean()
variance = accuracies.std()

AttributeError: 'super' object has no attribute '__sklearn_tags__'

cross validation / cv - runs the model with different train test split to identify the best split

##### Hyper Parameter Optimisation

In [36]:
#Improvising the ANN - Hyper parameter optimization

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


classifier = KerasClassifier(model = build_classifier)

parameters = {'batch_size': [10, 20],
              'epochs': [5, 6]}

              # Total combinations: 4

grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', n_jobs = -1, cv = 5)
grid_search = grid_search.fit(X_train, y_train)

grid_search.best_params_
grid_search.best_score_

AttributeError: 'super' object has no attribute '__sklearn_tags__'

##### Improvising the performance of ANN
- Increasing the number of hidden layers
- Increasing the number of epochs
- Fine-tuning the parameters - optimizers, batch_size, epochs
- Dropout regularization: Dropout(0.25)
Overfitting problem --> training accuracy increases, but test accuracy is low