NUMPY — Interview Critical Concepts
---

NDARRAY

- Numpy’s core object is ndarray

- Homogeneous → All elements same type
(python list is heterogenous therfore type checking nd overhead)

- Faster than Python list (C-level memory operations)
(Python is dynamically typed and interpreted. Every addition like a+b involves type checks, object creation, and reference counting. In C, the types are fixed and operations are compiled down to a few CPU instructions.)

- NumPy arrays are stored in contiguous memory which makes vectorized operations much faster than Python lists however in python lists , values are stored as memory references.


In [1]:
import numpy as np
a= np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


Vectorization (⭐ ⭐ ⭐ ⭐)

No loops → fast operations

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
print(c)

[5 7 9]


Broadcasting (⭐ ⭐ ⭐ ⭐)

Let arrays of different shapes work together

How does NumPy handle different shapes?
- By broadcasting smaller array over larger one.

In [5]:
a = np.array([1,2,3])
b=np.array([1])
print(a+b)

[2 3 4]


Shape & Reshaping (⭐ ⭐ ⭐)

In [7]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
print(a.reshape(2,3))
print(a.flatten())
print(a.T)

(6,)
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


Indexing & Slicing (⭐ ⭐ ⭐ ⭐)

In [8]:
print(a[1:3])
print(a[a>5])

[2 3]
[6]


Linear Algebra (⭐ ⭐ ⭐ ⭐)

Random module (⭐ ⭐ ⭐)

In [ ]:
print(np.random.rand(3,2))
# Create an array of the given shape and populate it with random samples of float numbers from a uniform distribution over [0, 1)

print(np.random.randn(3,2))
#Return a sample (or samples) from the "standard normal" distribution.

print(np.random.randint(1, 10, size=(2,4)))
# low,high,size,dtype



[[0.74937635 0.12210463]
 [0.07572757 0.55934602]
 [0.3885052  0.8814816 ]]
[[-0.6067572  -0.38302417]
 [ 1.42803953  0.14576416]
 [-1.11201275  0.34653985]]
[[7 3 5 6]
 [6 3 5 3]]
None


Stacking & Splitting


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c =np.vstack((a,b))
print(c)
print(np.hstack(c))



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [13]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

PANDAS — Interview Critical Concepts

Pandas is a fast, powerful Python library used for data manipulation and analysis. It provides two main data structures — Series (1‑D) and DataFrame (2‑D) — which make it easy to clean, transform, filter, aggregate, and analyze structured data.

It’s built on top of NumPy, so it’s optimized for performance and works great with large datasets.

Series & DataFrame

Difference:
- Series = 1D
- DataFrame = 2D table

In [15]:
import pandas as pd

In [18]:
a=pd.Series([1,2,3])
print(a)
pd.DataFrame({'A':[1,2],'B':[3,4]})


0    1
1    2
2    3
dtype: int64


A  B
0  1  3
1  2  4

Importing data

In [ ]:
pd.read_csv()
pd.read_excel()
pd.read_json()

| Function           | Why used        |
| ------------------ | --------------- |
| isnull()/notnull() | Missing values  |
| dropna()           | Remove null     |
| fillna()           | Replace null    |
| astype()           | Type conversion |
| rename()           | Clean headers   |


Selection & Filtering

In [22]:
df= pd.read_csv("Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [27]:
df.loc[df['Surname'] =='Walker',['CreditScore']]=0
# Access a group of rows and columns by label(s) or a boolean array.

In [28]:
df.loc[df['Surname'] =='Walker']['CreditScore']

697     0
1086    0
1547    0
1692    0
2127    0
2203    0
2534    0
2615    0
2755    0
3086    0
3129    0
3334    0
4828    0
4955    0
5429    0
5520    0
6185    0
6822    0
6871    0
7595    0
7625    0
8096    0
8795    0
9059    0
9506    0
9647    0
9682    0
9999    0
Name: CreditScore, dtype: int64

In [31]:
df.iloc[:2]
# Purely integer-location based indexing for selection by position.

df.iloc[lambda x: x.index % 2 == 0]

RowNumber  CustomerId      Surname  CreditScore Geography  Gender  Age  \
0             1    15634602     Hargrave          619    France  Female   42   
2             3    15619304         Onio          502    France  Female   42   
4             5    15737888     Mitchell          850     Spain  Female   43   
6             7    15592531     Bartlett          822    France    Male   50   
8             9    15792365           He          501    France    Male   44   
...         ...         ...          ...          ...       ...     ...  ...   
9990       9991    15798964   Nkemakonam          714   Germany    Male   33   
9992       9993    15657105  Chukwualuka          726     Spain    Male   36   
9994       9995    15719294         Wood          800    France  Female   29   
9996       9997    15569892    Johnstone          516    France    Male   35   
9998       9999    15682355    Sabbatini          772   Germany    Male   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
2          8  159660.80              3          1               0   
4          2  125510.82              1          1               1   
6          7       0.00              2          1               1   
8          4  142051.07              2          0               1   
...      ...        ...            ...        ...             ...   
9990       3   35016.60              1          1               0   
9992       2       0.00              1          1               0   
9994       2       0.00              2          0               0   
9996      10   57369.61              1          1               1   
9998       3   75075.31              2          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
2           113931.57       1  
4            79084.10       0  
6            10062.80       0  
8            74940.50       0  
...               ...     ...  
9990         53667.08       0  
9992        195192.40       0  
9994        167773.55       0  
9996        101699.77       0  
9998         92888.52       1  

[5000 rows x 14 columns]

In [32]:
df[df['CreditScore'] > 500]

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9994       9995    15719294       Wood          800    France  Female   29   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9994       2       0.00              2          0               0   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9994        167773.55       0  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  

[9330 rows x 14 columns]

GroupBy & Aggregations

In [33]:
df.groupby('Geography')['CreditScore'].mean()

Geography
France     648.095333
Germany    648.523316
Spain      649.978199
Name: CreditScore, dtype: float64

In [35]:
df['CreditScore'].agg(['mean','max'])

mean    648.6691
max     850.0000
Name: CreditScore, dtype: float64

In [36]:
df['new'] = df['CreditScore'].apply(lambda x: x*2)


In [38]:
df.sort_values('new')

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
8795       8796    15716608     Walker            0     Spain    Male   38   
3334       3335    15702300     Walker            0    France    Male   27   
1692       1693    15809006     Walker            0    France    Male   23   
1086       1087    15708063     Walker            0    France    Male   36   
2534       2535    15803804     Walker            0   Germany  Female   35   
...         ...         ...        ...          ...       ...     ...  ...   
7470       7471    15602456  Afanasyev          850   Germany  Female   47   
4316       4317    15720774      P'eng          850     Spain    Male   44   
3609       3610    15657868      Serra          850   Germany    Male   40   
38           39    15717426  Armstrong          850    France    Male   36   
9949       9950    15798615        Wan          850    France  Female   47   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
8795       2       0.00              3          1               0   
3334       5       0.00              2          0               0   
1692       7  113758.48              2          0               0   
1086       2  100749.50              3          0               0   
2534       5  103214.71              1          1               0   
...      ...        ...            ...        ...             ...   
7470       4   99219.47              2          1               1   
4316       7   89118.26              1          1               0   
3609       6   94607.08              1          1               0   
38         7       0.00              1          1               1   
9949       9  137301.87              1          1               0   

      EstimatedSalary  Exited   new  
8795         67029.82       1     0  
3334        120893.07       0     0  
1692         84077.60       0     0  
1086         70758.37       1     0  
2534        172172.70       0     0  
...               ...     ...   ...  
7470        122141.13       0  1700  
4316        104240.77       1  1700  
3609         36690.49       0  1700  
38           40812.90       0  1700  
9949         44351.77       0  1700  

[10000 rows x 15 columns]

Date-time handling

In [ ]:
pd.to_datetime()
df['date'].dt.year

MATPLOTLIB — Interview Critical Concepts

Matplotlib is a powerful Python library used for data visualization. It allows you to create a wide range of static, animated, and interactive plots — such as line charts, bar charts, histograms, scatter plots, and more.

It’s the foundation of most Python plotting libraries, including Seaborn and Pandas’ built‑in plotting.

In [39]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(x,y)
plt.scatter(x,y)
plt.hist(data, bins=20)
plt.bar(labels,values)
fig, ax = plt.subplots(2,2)
plt.xlabel()
plt.ylabel()
plt.legend()
plt.title()




NUMPY — Interview Questions + Code Challenges

Q1. Create a NumPy array from a Python list

Q2. Find:

shape

number of dimensions

data type

Q3. Create a 3x3 matrix filled with zeros and a 3x3 matrix filled with ones.

Q4. Create an array with values from 10 to 50 (step 5)

Q5. Multiply two arrays element-wise:


In [53]:
import numpy as np

a = np.array([1,2,3,4])
b = np.zeros((3,3))
c = np.ones((2,2))
d = np.arange(0,10,2)
e = np.linspace(0, 1, 5)

print(a, b, c, d, e)


a.shape
a.dtype

[1 2 3 4] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


dtype('int64')

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)     # (2, 3)
print(arr.ndim)      # 2
print(arr.dtype)     # int64
print(arr.size)      # 6 # total num of elements in array


(2, 3)
2
int64
6


In [55]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr[0,1])    # 20
print(arr[:,1])    # [20 50 80]
print(arr[1,:])    # [40 50 60]
print(arr[0:2,0:2])


20
[20 50 80]
[40 50 60]
[[10 20]
 [40 50]]


In [56]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** 2)
print(np.sqrt(a))


[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]


Q6. Normalize the following array (0–1 scale):
arr = np.array([12, 15, 10, 20, 25])

Q7. Reshape this into 2x3
arr = np.array([1,2,3,4,5,6])

Q8 Perform matrix multiplication
A = [[1,2],
     [3,4]]
B = [[5,6],
     [7,8]]

Q9. Find:

Mean, Median, Standard Deviation
data = [20,30,40,50,60]

Q10. Generate 100 random values from normal distribution

Q11. Replace all values > 50 with 50 in an array

Q12. Find index of max value in array

Q13. Stack 2 arrays vertically and horizontally

Q14. Find eigenvalues of matrix




In [49]:
arr = np.array([1,2,3,4,5,6])
arr = arr.apply(lambda x :(x - arr.min()) / (arr.max() - arr.min()))
arr

AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [50]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A @ B)                     # matrix multiplication
print(np.dot(A,B))
print(np.linalg.inv(A))
print(np.linalg.det(A))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [58]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr + np.array([10,20,30]))


[[11 22 33]
 [14 25 36]]


In [59]:
np.std(arr)

np.float64(1.707825127659933)

In [ ]:
# Generate 100 random values from normal distribution

import numpy as np

# Generate 100 random values from a normal distribution
# mean = 0, standard deviation = 1 (default)
data = np.random.normal(loc=0, scale=1, size=100)
# same as np.random.randn
print(data)


[-0.88523035 -0.41218848 -0.4826188   0.16416482  0.23309524  0.11799461
  1.46237812  1.53871497 -2.43910582  0.60344123 -0.25104397 -0.16386712
 -1.47632969  1.48698096 -0.02445518  0.35555132  0.41701111  0.83246186
 -0.29339915 -0.02983857  0.09512578  0.66465434 -0.1402185  -0.0331934
 -0.74907652 -0.77838201  0.94884286  1.58085059 -0.36817094  0.37556463
 -1.19315823 -0.4090519  -0.44674147  1.52424163  0.3229998  -1.39341694
 -2.17833425 -1.04389641  0.17269371  0.32419877  0.74585954 -1.83658324
  0.56446424  0.02550067  0.47319325  0.6591906   2.34074633  1.07098519
  0.09641648  0.41910211 -0.95302779 -1.0478706  -1.87567677 -1.36678214
  0.63630511 -0.90672067  0.47604259  1.30366127  0.21158701  0.59704465
 -0.89633518 -0.11198782  1.46894129 -1.12389833  0.9500054   1.72651647
  0.45788508 -1.68428738  0.32684522 -0.08111895  0.46779475  0.73612235
 -0.77970188 -0.84389636 -0.15053386 -0.96555767  0.15048908 -0.11342125
  2.63352822 -1.02509089 -0.78204783  0.42394307  0.

In [61]:
import numpy as np

arr = np.array([10, 25, 7, 30, 18])

# Find index of max value
index = np.argmax(arr)

print("Index:", index)
print("Max value:", arr[index])


Index: 3
Max value: 30


PANDAS — Real-World Interview Challenges

In [86]:
import pandas as pd

data = {
'Name': ['A','B','C','D','E'],
'Age': [22,25,None,29,28],
'Salary': [40000,50000,45000,None,70000],
'Department': ['HR','Tech','Tech','Marketing','HR']
}

df = pd.DataFrame(data)


In [87]:
df

Name   Age   Salary Department
0    A  22.0  40000.0         HR
1    B  25.0  50000.0       Tech
2    C   NaN  45000.0       Tech
3    D  29.0      NaN  Marketing
4    E  28.0  70000.0         HR

In [88]:
df[0:3]

Name   Age   Salary Department
0    A  22.0  40000.0         HR
1    B  25.0  50000.0       Tech
2    C   NaN  45000.0       Tech

In [89]:
df.isnull().sum()

Name          0
Age           1
Salary        1
Department    0
dtype: int64

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        5 non-null      object 
 1   Age         4 non-null      float64
 2   Salary      4 non-null      float64
 3   Department  5 non-null      object 
dtypes: float64(2), object(2)
memory usage: 288.0+ bytes


In [91]:
df.describe()

Age        Salary
count   4.000000      4.000000
mean   26.000000  51250.000000
std     3.162278  13149.778198
min    22.000000  40000.000000
25%    24.250000  43750.000000
50%    26.500000  47500.000000
75%    28.250000  55000.000000
max    29.000000  70000.000000

In [98]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [99]:
df

Name   Age   Salary Department
0    A  22.0  40000.0         HR
1    B  25.0  50000.0       Tech
2    C  26.0  45000.0       Tech
3    D  29.0      NaN  Marketing
4    E  28.0  70000.0         HR

In [101]:
df.groupby('Department')['Salary'].mean()

df.groupby('Department').agg({
    'Salary':'mean',
    'Age':'max'
})


Salary   Age
Department               
HR          55000.0  28.0
Marketing       NaN  29.0
Tech        47500.0  26.0

In [102]:
df.sort_values(by='Age', ascending=False)


Name   Age   Salary Department
3    D  29.0      NaN  Marketing
4    E  28.0  70000.0         HR
2    C  26.0  45000.0       Tech
1    B  25.0  50000.0       Tech
0    A  22.0  40000.0         HR

In [103]:
df['Age'] = df['Age'].apply(lambda x: x+1)


In [ ]:
df = pd.merge(df1, df2, on="id", how="inner")
#column-based joins, you’d typically use merge()

# based on index
result_inner = df1.join(df2, how='inner')


NameError: name 'df1' is not defined

Perfect. Here is your **interview-focused theoretical Q&A set for Python, NumPy, Pandas, and Matplotlib** — written exactly in the way interviewers expect answers. Keep this as your **last-day revision sheet**.

---

# 🔹 PYTHON – Theoretical Interview Questions + Answers

### 1. What makes Python different from other languages?

Python is:

* Interpreted (no compilation step)
* Dynamically typed - Python is dynamically typed, meaning variable types are determined at runtime. You don’t declare types explicitly, and a variable can hold values of different types at different points in the program.
* High-level
* Easy syntax
* Large ecosystem (AI/ML, Web, Automation)

---

### 2. Difference between list and tuple?

| List             | Tuple            |
| ---------------- | ---------------- |
| Mutable          | Immutable        |
| Slower           | Faster           |
| Uses more memory | Uses less memory |
| Uses []          | Uses ()          |

Tuple is used when data should not change.

---

### 3. What is a generator?

A generator is a special type of function that **returns one value at a time** using the `yield` keyword instead of returning all values at once.
It saves memory and is efficient for large data.

Example:

```python
def nums():
    for i in range(10):
        yield i
```

---

### 4. What are decorators?

Decorators are functions that **modify the behavior of another function without changing its code**.

Used for:

* Authentication
* Logging
* Timing
* Validation

Example:

```python
def my_decorator(func):
    def wrapper():
        print("Before")
        func()
        print("After")
    return wrapper
```

---

### 5. Shallow vs Deep copy?

| Shallow Copy     | Deep Copy            |
| ---------------- | -------------------- |
| Copies reference | Copies entire object |
| Changes reflect  | No changes reflect   |
| Uses `copy()`    | Uses `deepcopy()`    |

---

### 6. What is GIL in Python?

GIL (Global Interpreter Lock) allows only **one thread to execute Python bytecode at a time.**
This is why multithreading is less effective in CPU-bound tasks, but works well in I/O-bound tasks.

---

### 7. Difference between multithreading & multiprocessing?

| Multithreading         | Multiprocessing  |
| ---------------------- | ---------------- |
| Same memory            | Separate memory  |
| Faster for I/O         | Best for CPU     |
| Affected by GIL        | Not affected     |
| Low actual parallelism | True parallelism |

---

### 8. What is memory management in Python?

Python does:
✅ Automatic memory allocation
✅ Garbage collection
✅ Reference counting

Unused objects are deleted automatically.

---

# 🔹 NUMPY – Interview Theoretical Q&A

### 1. Why is NumPy faster than lists?

Because it:

* Uses C backend
* Stores elements in contiguous memory
* Uses vectorized operations
* Avoids Python loops

---

### 2. What is ndarray?

It is a homogeneous multi-dimensional array in NumPy.

All elements must be of same type (int, float, etc).

---

### 3. What is broadcasting?

NumPy automatically adjusts shape of smaller array to perform element-wise operations.

Example:

```python
[1,2,3] + [[1],[2],[3]]
```

---

### 4. Difference: reshape vs resize

| reshape          | resize            |
| ---------------- | ----------------- |
| Returns new view | Modifies original |
| Safer            | Permanent         |

---

### 5. Dot vs @ operator

Both are used for **matrix multiplication**.

`@` was introduced in Python 3.5 as cleaner syntax.

```python
A @ B
np.dot(A,B)
```

---

### 6. What are universal functions (ufuncs)?

They work on NumPy arrays element-wise:

* np.sqrt
* np.exp
* np.log
* np.sum

They are faster than loops.

---

### 7. What is vectorization?

Vectorization removes explicit loops and uses NumPy operations for excellent speed.

Example:

```python
arr * 2
```

instead of loop.

---

# 🔹 PANDAS – Interview Q&A

### 1. Difference between Series & DataFrame

| Series      | DataFrame          |
| ----------- | ------------------ |
| 1D          | 2D                 |
| Like column | Like table         |
| Has index   | Has rows & columns |

---

### 2. What is loc and iloc?

| loc               | iloc         |
| ----------------- | ------------ |
| Label based       | Index based  |
| Includes end      | Excludes end |
| uses column names | uses numbers |

---

### 3. What is groupby?

Used for **splitting → applying → combining** operations.

Mostly used for:

* Aggregation
* Feature engineering
* Analysis

---

### 4. How to handle missing data?

* `dropna()`
* `fillna()`
* mean/median/mode
* interpolation

---

### 5. Merge vs join?

| merge         | join        |
| ------------- | ----------- |
| Column based  | Index based |
| Like SQL join | Same        |

---

### 6. What is apply()?

Used to apply function row-wise or column-wise.

Used for:
✅ Feature engineering
✅ Transformations

---

### 7. Pandas vs NumPy?

| Pandas          | NumPy            |
| --------------- | ---------------- |
| Structured data | Numerical arrays |
| Labels          | No labels        |
| Useful for ML   | Useful for Math  |

---

# 🔹 MATPLOTLIB – Interview Q&A

### 1. Why use Matplotlib?

To visualize data for:

* Patterns
* Trends
* Distribution
* Outliers

---

### 2. Types of plots in Matplotlib

| Plot      | Use             |
| --------- | --------------- |
| Line      | Trend over time |
| Scatter   | Relationship    |
| Bar       | Comparison      |
| Histogram | Distribution    |
| Box Plot  | Outliers        |

---

### 3. What is marker?

Controls point style in plot:

```python
plt.plot(x, y, marker='o')
```

---

### 4. Purpose of histogram?

To see:
✅ Data distribution
✅ Skewness
✅ Outliers

---

### 5. Difference between seaborn & matplotlib?

| Matplotlib       | Seaborn        |
| ---------------- | -------------- |
| Low level        | High level     |
| More control     | More beautiful |
| Base for seaborn | Built on mpl   |

---

# 🎯 FINAL TIP FOR INTERVIEWS

When answering, always use this format:

> **Concept → Why important → One-line example**

Example:

❌ Bad: “GroupBy is used to group data”

✅ Good:
"GroupBy in pandas is used to split, apply, and aggregate data. It is used heavily in feature engineering. Example: calculating average salary by department."

---





## 🎯 Interview Answer

### 1. **Global Interpreter Lock (GIL)**
- **Concept**: In CPython, the GIL is a mutex that ensures only one thread executes Python bytecode at a time.  
- **Importance**: It simplifies memory management but prevents true parallel execution of threads on multi-core CPUs.  
- **Impact**: Threads are useful for I/O-bound tasks but inefficient for CPU-bound tasks because of the GIL.

---

### 2. **Multithreading**
- **Concept**: Multiple threads run within the same process, sharing memory space.  
- **Importance**: Best for **I/O-bound tasks** (network requests, file I/O) where threads spend time waiting.  
- **Limitation**: Due to the GIL, only one thread runs Python code at a time, so CPU-heavy tasks don’t benefit.  
- **Example**:
  ```python
  import threading

  def task():
      print("Thread running")

  t1 = threading.Thread(target=task)
  t2 = threading.Thread(target=task)
  t1.start(); t2.start()
  t1.join(); t2.join()
  ```
  Output:  
  ```
  Thread running
  Thread running
  ```

---

### 3. **Multiprocessing**
- **Concept**: Multiple processes run independently, each with its own Python interpreter and memory space.  
- **Importance**: Bypasses the GIL, enabling **true parallelism** across multiple CPU cores. Ideal for **CPU-bound tasks** like heavy computations.  
- **Example**:
  ```python
  from multiprocessing import Process

  def task():
      print("Process running")

  p1 = Process(target=task)
  p2 = Process(target=task)
  p1.start(); p2.start()
  p1.join(); p2.join()
  ```
  Output (order may vary):  
  ```
  Process running
  Process running
  ```

---

### ✅ Final Summary
- **GIL**: Only one thread executes Python code at a time.  
- **Multithreading**: Good for I/O-bound tasks, limited by GIL.  
- **Multiprocessing**: Good for CPU-bound tasks, bypasses GIL with true parallelism.  

---
